export interface Course {
  id: number;
  title: string;
  instructors: string;
  rating: number;
  reviews: number;
  price: number;
  originalPrice: number;
  image: string;
  badges: string[];
  category: string;
  topics: string[];
  isNew?: boolean;
}

export const navigationLinks = [
  { name: "Plans & Pricing", href: "#" },
  { name: "Live Classes", href: "#" },
  { name: "Tech on Cosmostaker", href: "#" },
]

export const categories: string[] = [
  "Data Science",
  "IT Certifications",
  "Leadership",
  "Web Development",
  "Communication",
  "Business Analytics & Intelligence",
]

export const popularTopics = [
  { name: "Data Science", count: "7M+ learners" },
  { name: "Python", count: "47.7M+ learners" },
  { name: "Machine Learning", count: "8M+ learners" },
  { name: "Deep Learning", count: "5M+ learners" },
  { name: "Artificial Intelligence (AI)", count: "8M+ learners" },
  { name: "Statistics", count: "9M+ learners" },
  { name: "R", count: "8M+ learners" },
]

export const coursesDatabase: Course[] = [
  {
    id: 1,
    title: "The Complete AI Guide: Learn ChatGPT, Generative AI & More",
    instructors: "Julian Melanson, Benza Maman, Leap Y.",
    rating: 4.5,
    reviews: 45368,
    price: 549,
    originalPrice: 2699,
    image: "https://img-c.udemycdn.com/course/240x135/3600048_b195_20.jpg",
    badges: ["Premium", "Bestseller"],
    category: "Data Science",
    topics: ["ChatGPT", "Artificial Intelligence (AI)", "Machine Learning"],
  },
  {
    id: 2,
    title: "The Complete AI-Powered Copywriting Course & ChatGPT Guide",
    instructors: "Ing. Tomas Moravek, Learn Digital",
    rating: 4.3,
    reviews: 1797,
    price: 549,
    originalPrice: 3099,
    image: "https://img-c.udemycdn.com/course/240x135/5231088_b1e8_2.jpg",
    badges: ["Premium"],
    category: "Communication",
    topics: ["ChatGPT", "Artificial Intelligence (AI)"],
  },
  {
    id: 3,
    title: "ChatGPT, DeepSeek, Grok and 30+ More AI Marketing Assistants",
    instructors: "Anton Voroniuk, Anton Voroniuk Support",
    rating: 4.4,
    reviews: 526,
    price: 549,
    originalPrice: 799,
    image: "https://img-c.udemycdn.com/course/240x135/5672302_cfed.jpg",
    badges: ["Premium"],
    category: "Business Analytics & Intelligence",
    topics: ["ChatGPT", "Artificial Intelligence (AI)"],
  },
  {
    id: 4,
    title: "The Complete ChatGPT Guide From Zero to Hero - 2025",
    instructors: "A.M.A.M Mubeen (Expert In Tally &",
    rating: 4.2,
    reviews: 477,
    price: 499,
    originalPrice: 799,
    image: "https://img-c.udemycdn.com/course/240x135/5672302_cfed.jpg",
    badges: [],
    category: "IT Certifications",
    topics: ["ChatGPT"],
  },
  {
    id: 5,
    title: "Python for Data Science and Machine Learning Bootcamp",
    instructors: "Jose Portilla",
    rating: 4.6,
    reviews: 125789,
    price: 649,
    originalPrice: 3499,
    image: "https://img-c.udemycdn.com/course/240x135/5170404_d282_9.jpg",
    badges: ["Premium", "Bestseller"],
    category: "Data Science",
    topics: ["Python", "Data Science", "Machine Learning"],
  },
  {
    id: 6,
    title: "Machine Learning A-Z: Hands-On Python & R In Data Science",
    instructors: "Kirill Eremenko, Hadelin de Ponteves",
    rating: 4.5,
    reviews: 158964,
    price: 549,
    originalPrice: 3299,
    image: "https://img-c.udemycdn.com/course/240x135/3600048_b195_20.jpg",
    badges: ["Premium", "Bestseller"],
    category: "Data Science",
    topics: ["Machine Learning", "Python", "Data Science"],
  },
  {
    id: 7,
    title: "Deep Learning Specialization",
    instructors: "Andrew Ng",
    rating: 4.8,
    reviews: 45698,
    price: 749,
    originalPrice: 4999,
    image: "https://img-c.udemycdn.com/course/240x135/5170404_d282_9.jpg",
    badges: ["Premium", "Bestseller"],
    category: "Data Science",
    topics: ["Deep Learning", "Machine Learning", "Artificial Intelligence (AI)"],
  },
  {
    id: 8,
    title: "Statistics for Data Science and Business Analysis",
    instructors: "365 Careers",
    rating: 4.5,
    reviews: 28745,
    price: 449,
    originalPrice: 1999,
    image: "https://img-c.udemycdn.com/course/240x135/5170404_d282_9.jpg",
    badges: ["Premium"],
    category: "Data Science",
    topics: ["Statistics", "Data Science, Machine Learning"],
  },
  {
    id: 9,
    title: "Natural Language Processing with Python",
    instructors: "Lazy Programmer Inc.",
    rating: 4.6,
    reviews: 12458,
    price: 649,
    originalPrice: 2999,
    image: "https://img-c.udemycdn.com/course/240x135/5170404_d282_9.jpg",
    badges: ["Premium"],
    category: "Data Science",
    topics: ["Natural Language Processing", "Python", "Artificial Intelligence (AI)"],
  },
  {
    id: 10,
    title: "Web Development Bootcamp 2025",
    instructors: "Colt Steele",
    rating: 4.7,
    reviews: 215478,
    price: 549,
    originalPrice: 3499,
    image: "https://img-c.udemycdn.com/course/240x135/5170404_d282_9.jpg",
    badges: ["Premium", "Bestseller"],
    category: "Web Development",
    topics: ["Python", "JavaScript"],
  },
  {
    id: 11,
    title: "Leadership: Practical Leadership Skills",
    instructors: "Chris Croft",
    rating: 4.5,
    reviews: 32145,
    price: 449,
    originalPrice: 1999,
    image: "https://img-c.udemycdn.com/course/240x135/3600048_b195_20.jpg",
    badges: ["Premium", "Bestseller"],
    category: "Leadership",
    topics: [],
  },
  {
    id: 12,
    title: "Business Intelligence with Power BI",
    instructors: "Maven Analytics",
    rating: 4.6,
    reviews: 18745,
    price: 549,
    originalPrice: 2499,
    image: "https://img-c.udemycdn.com/course/240x135/3600048_b195_20.jpg",
    badges: ["Premium"],
    category: "Business Analytics & Intelligence",
    topics: ["Data Science"],
  },
]

export const popularCourses = [
  {
    id: 1,
    title: "100 Days of Code: The Complete Python Pro Bootcamp for 2025",
    instructors: ["Dr. Angela Yu", "Developer and Lead Instructor"],
    rating: 4.7,
    reviewCount: 241640,
    students: 1452344,
    price: 549,
    originalPrice: 1699,
    image: "https://img-c.udemycdn.com/course/240x135/2776760_f176_10.jpg",
  },
  {
    id: 2,
    title: "The Complete Full-Stack Web Development Bootcamp",
    instructors: ["Dr. Angela Yu", "Developer and Lead Instructor"],
    rating: 4.7,
    reviewCount: 122055,
    students: 654321,
    price: 499,
    originalPrice: 1699,
    image: "https://img-c.udemycdn.com/course/240x135/2776760_f176_10.jpg",
  },
  {
    id: 3,
    title: "[NEW] Ultimate AWS Certified Cloud Practitioner - CLF-C02 2025",
    instructors: ["Stephane Maarek", "AWS Certified Cloud Practitioner"],
    rating: 4.7,
    reviewCount: 153075,
    students: 876543,
    price: 549,
    originalPrice: 1699,
    image: "https://img-c.udemycdn.com/course/240x135/3142166_a637_3.jpg",
  },
  {
    id: 4,
    title: "Ultimate AWS Certified Solutions Architect Associate SAA-C03 2025",
    instructors: ["Stephane Maarek", "AWS Certified Cloud Practitioner"],
    rating: 4.7,
    reviewCount: 187654,
    students: 932456,
    price: 549,
    originalPrice: 1699,
    image: "https://img-c.udemycdn.com/course/240x135/3142166_a637_3.jpg",
  },
  {
    id: 5,
    title: "Ultimate AWS Certified Solutions Architect Associate SAA-C03 2025",
    instructors: ["Stephane Maarek", "AWS Certified Cloud Practitioner"],
    rating: 4.7,
    reviewCount: 187654,
    students: 932456,
    price: 549,
    originalPrice: 1699,
    image: "https://img-c.udemycdn.com/course/240x135/6100015_1979_4.jpg",
  },
  {
    id: 6,
    title: "Ultimate AWS Certified Solutions Architect Associate SAA-C03 2025",
    instructors: ["Stephane Maarek", "AWS Certified Cloud Practitioner"],
    rating: 4.7,
    reviewCount: 187654,
    students: 932456,
    price: 549,
    originalPrice: 1699,
    image: "https://img-c.udemycdn.com/course/240x135/1570206_26c6_6.jpg",
  },
  {
    id: 7,
    title: "Ultimate AWS Certified Solutions Architect Associate SAA-C03 2025",
    instructors: ["Stephane Maarek", "AWS Certified Cloud Practitioner"],
    rating: 4.7,
    reviewCount: 187654,
    students: 932456,
    price: 549,
    originalPrice: 1699,
    image: "https://img-c.udemycdn.com/course/240x135/5993822_2c2a_7.jpg",
  }
]


export const luxuryHomes = [
  {
    id: 1,
    price: 2050000,
    beds: 5,
    baths: 3,
    sqft: 3200,
    address: "1729 42nd Avenue SE",
    city: "Spokane",
    state: "WA",
    zip: "99208",
    type: "Multi-Family Home",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=600&h=400&auto=format&fit=crop",
    new: true,
  },
  {
    id: 2,
    price: 1350000,
    beds: 4,
    baths: 3,
    sqft: 2400,
    address: "1508 E Creekview Dr",
    city: "Spokane",
    state: "WA",
    zip: "99207",
    type: "Single-Family Home",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=600&h=400&auto=format&fit=crop",
    new: true,
  },
  {
    id: 3,
    price: 1200000,
    beds: 4,
    baths: 3,
    sqft: 2100,
    address: "1426 N Lincoln St",
    city: "Spokane",
    state: "WA",
    zip: "99207",
    type: "Multi-Family Home",
    image: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?q=80&w=600&h=400&auto=format&fit=crop",
    new: true,
    lot: 0.25,
  },
  {
    id: 4,
    price: 4300000,
    beds: 6,
    baths: 7,
    sqft: 5267,
    address: "4507 N Boulder Park Ln",
    city: "Spokane",
    state: "WA",
    zip: "99207",
    type: "Single-Family Home",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=600&h=400&auto=format&fit=crop",
    new: true,
  },
  {
    id: 5,
    price: 4300000,
    beds: 6,
    baths: 7,
    sqft: 5267,
    address: "4507 N Boulder Park Ln",
    city: "Spokane",
    state: "WA",
    zip: "99207",
    type: "Single-Family Home",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=600&h=400&auto=format&fit=crop",
    new: true,
  },
  {
    id: 6,
    price: 4300000,
    beds: 6,
    baths: 7,
    sqft: 5267,
    address: "4507 N Boulder Park Ln",
    city: "Spokane",
    state: "WA",
    zip: "99207",
    type: "Single-Family Home",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=600&h=400&auto=format&fit=crop",
    new: true,
  },
  {
    id: 7,
    price: 4300000,
    beds: 6,
    baths: 7,
    sqft: 5267,
    address: "4507 N Boulder Park Ln",
    city: "Spokane",
    state: "WA",
    zip: "99207",
    type: "Single-Family Home",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=600&h=400&auto=format&fit=crop",
    new: true,
  },
]

export const testimonials = [
  {
    id: 1,
    text: "Because of this course I was able to clear multiple interviews. Thanks for making such wonderful content.",
    author: "Richard S.",
    course: "Business Intelligence (BI)",
  },
  {
    id: 2,
    text: "This has helped me so much in my career. I started as a frontend engineer and eventually transitioned to full stack engineer with the help of this course.",
    author: "Charlotte W.",
    course: "Go-getting course",
  },
  {
    id: 3,
    text: "Today I am a software developer, and I consider a significant part of my success to the solid foundation laid by this course.",
    author: "Martha A.",
    course: "Java course",
  },
  {
    id: 4,
    text: "I would highly recommend this Web Development Bootcamp to anyone interested in pursuing a career in web development. It provides the foundation to enhance their skills in the field.",
    author: "Anna P.",
    course: "Web Development course",
  },
]

export const footerLinks = [
  { name: "About us", href: "#" },
  { name: "Careers", href: "#" },
  { name: "Accessibility", href: "#" },
  { name: "Feedback", href: "#" },
  { name: "Media room", href: "#" },
  { name: "Ad Choices", href: "#" },
  { name: "Advertise with us", href: "#" },
  { name: "Agent support", href: "#" },
  { name: "Privacy", href: "#" },
  { name: "Terms", href: "#" },
  { name: "Home Made", href: "#" },
  { name: "Tech Blog", href: "#" },
  { name: "Agent Blog", href: "#" },
  { name: "Sitemap", href: "#" },
  { name: "Do Not Sell or Share My Personal Information", href: "#" },
]

export const socialLinks = [
  { name: "Facebook", href: "#", icon: "facebook" },
  { name: "Twitter", href: "#", icon: "twitter" },
  { name: "LinkedIn", href: "#", icon: "linkedin" },
  { name: "Instagram", href: "#", icon: "instagram" },
  { name: "YouTube", href: "#", icon: "youtube" },
]

export const trustedCompanies = [
  { id: 1, name: "Volkswagen", logo: "https://cms-images.udemycdn.com/content/mueb2ve09x/svg/volkswagen_logo.svg?position=c&quality=80&x.app=portals" },
  { id: 2, name: "Samsung", logo: "https://cms-images.udemycdn.com/content/2gevcc0kxt/svg/samsung_logo.svg?position=c&quality=80&x.app=portals" },
  { id: 3, name: "Cisco", logo: "https://cms-images.udemycdn.com/content/mueb2ve09x/svg/cisco_logo.svg?position=c&quality=80&x.app=portals" },
  { id: 4, name: "Vimeo", logo: "https://cms-images.udemycdn.com/content/ryaowrcjb2/svg/vimeo_logo_resized-2.svg?position=c&quality=80&x.app=portals" },
  { id: 5, name: "P&G", logo: "https://cms-images.udemycdn.com/content/bthyo156te/svg/procter_gamble_logo.svg?position=c&quality=80&x.app=portals" },
  { id: 6, name: "Hewlett Packard Enterprise", logo: "https://cms-images.udemycdn.com/content/luqe0d6mx2/svg/hewlett_packard_enterprise_logo.svg?position=c&quality=80&x.app=portals" },
  { id: 7, name: "Citi", logo: "https://cms-images.udemycdn.com/content/siaewwmkch/svg/citi_logo.svg?position=c&quality=80&x.app=portals" },
  { id: 8, name: "Ericsson", logo: "https://cms-images.udemycdn.com/content/swmv0okrlh/svg/ericsson_logo.svg?position=c&quality=80&x.app=portals" },
];

export const buttons = [
  { label: "My Learnings", index: 0 },
  { label: "Live Classes", index: 1 },
  { label: "Teach on CU", index: 2 },
  { label: "Pricing & Subscriptions", index: 3 },
  { label: "Trainings & Certificates", index: 4 },
  { label: "Contact Us", index: 5 },
];

export const searchOptions = ["Courses", "Trainers", "Certificates"];

export const heroTitle = "The #1 site for lifelong learners & experienced trainers.";

export const userRoles = ["Student", "Trainer"];

export const ctaContent = {
  heading: "Come Teach with us?",
  backgroundImage: "/ebook.png"
};

export const courses = [
  {
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=600&h=400&crop=faces&fit=crop",
    title: "Data Science & Machine Learning",
    description: "Expert in AI, Data Science, and Deep Learning with 10+ years of experience",
    instructors: "Krish Naik",
    rating: 4.8,
    ratingsCount: 9800,
    totalHours: 1500,
    lectures: 120,
    level: "Expert",
    price: 499,
    originalPrice: 2999,
    new: true,
  },
  {
    image: "https://images.unsplash.com/photo-1521119989659-a83eee488004?q=80&w=600&h=400&crop=faces&fit=crop",
    title: "JavaScript & Web Development",
    description: "Full-Stack JavaScript Developer with expertise in React, Node.js, and TypeScript",
    instructors: "John Doe",
    rating: 4.7,
    ratingsCount: 8700,
    totalHours: 1200,
    lectures: 200,
    level: "Intermediate",
    price: 699,
    originalPrice: 3499,
    new: false,
  },
  {
    image: "https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=600&h=400&crop=faces&fit=crop",
    title: "React & Next.js Development",
    description: "Passionate Frontend Engineer teaching modern web development best practices",
    instructors: "Emily White",
    rating: 4.9,
    ratingsCount: 1020,
    totalHours: 1000,
    lectures: 180,
    level: "Advanced",
    price: 899,
    originalPrice: 3999,
    new: true,
  },
  {
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=600&h=400&crop=faces&fit=crop",
    title: "Full-Stack Web Development",
    description: "Full-stack engineer covering everything from backend APIs to frontend UI",
    instructors: "David Green",
    rating: 4.8,
    ratingsCount: 1130,
    totalHours: 1400,
    lectures: 250,
    level: "Expert",
    price: 899,
    originalPrice: 3999,
    new: true,
  },
  {
    image: "https://images.unsplash.com/photo-1554151228-14d9def656e4?q=80&w=600&h=400&crop=faces&fit=crop",
    title: "Machine Learning & Web Development",
    description: "Helping designers master UX, UI, and product design fundamentals",
    instructors: "Sophia Brown",
    rating: 4.6,
    ratingsCount: 7200,
    totalHours: 800,
    lectures: 150,
    level: "Beginner to Advanced",
    price: 799,
    originalPrice: 3499,
    new: false,
  },
  {
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=600&h=400&crop=faces&fit=crop",
    title: "Cybersecurity & Ethical Hacking",
    description: "Cybersecurity professional specializing in penetration testing and ethical hacking",
    instructors: "James Wilson",
    rating: 4.7,
    ratingsCount: 8600,
    totalHours: 1100,
    lectures: 220,
    level: "Intermediate",
    price: 899,
    originalPrice: 3999,
    new: true,
  },
];


export const propertyDetails = {
  name: "Top Trainers",
  location: "All Locations",
  properties: luxuryHomes,
};

export const trustedMessage = "Trusted by over 16,000 companies and millions of learners around the world";
export const testimonial = "See what others are achieving through learning";