export interface Course {
  id: number;
  title: string;
  instructors: string;
  rating: number;
  reviews: number;
  price: number;
  originalPrice: number;
  image: string;
  badges: string[];
  category: string;
  topics: string[];
  isNew?: boolean;
}

export const navigationLinks = [
  { name: "Plans & Pricing", href: "#" },
  { name: "Live Classes", href: "#" },
  { name: "Tech on Cosmostaker", href: "#" },
]

export const categories: string[] = [
  "Data Science",
  "IT Certifications",
  "Leadership",
  "Web Development",
  "Communication",
  "Business Analytics & Intelligence",
]

export const realEstateCategories: string[] = [
  "Residential Properties",
  "Commercial Properties",
  "Luxury Homes",
  "Apartments & Condos",
  "Vacation Rentals",
];


export const popularTopics = [
  { name: "Data Science", count: "7M+ learners" },
  { name: "Python", count: "47.7M+ learners" },
  { name: "Machine Learning", count: "8M+ learners" },
  { name: "Deep Learning", count: "5M+ learners" },
  { name: "Artificial Intelligence (AI)", count: "8M+ learners" },
  { name: "Statistics", count: "9M+ learners" },
  { name: "R", count: "8M+ learners" },
]
export const realEstatePopularTopics = [
  { name: "Residential Properties", count: "5M+ viewers" },
  { name: "Real Estate Investing", count: "8M+ viewers" },
  { name: "Property Flipping", count: "4M+ viewers" },
  { name: "Rental Property Management", count: "6M+ viewers" },
  { name: "Luxury Real Estate", count: "3M+ viewers" },
  { name: "Commercial Real Estate", count: "7M+ viewers" },
  { name: "Mortgage & Financing", count: "5.5M+ viewers" },
];

export const coursesDatabase: Course[] = [
  {
    id: 1,
    title: "The Complete AI Guide: Learn ChatGPT, Generative AI & More",
    instructors: "Julian Melanson, Benza Maman, Leap Y.",
    rating: 4.5,
    reviews: 45368,
    price: 549,
    originalPrice: 2699,
    image: "https://img-c.udemycdn.com/course/240x135/3600048_b195_20.jpg",
    badges: ["Premium", "Bestseller"],
    category: "Data Science",
    topics: ["ChatGPT", "Artificial Intelligence (AI)", "Machine Learning"],
  },
  {
    id: 2,
    title: "The Complete AI-Powered Copywriting Course & ChatGPT Guide",
    instructors: "Ing. Tomas Moravek, Learn Digital",
    rating: 4.3,
    reviews: 1797,
    price: 549,
    originalPrice: 3099,
    image: "https://img-c.udemycdn.com/course/240x135/5231088_b1e8_2.jpg",
    badges: ["Premium"],
    category: "Communication",
    topics: ["ChatGPT", "Artificial Intelligence (AI)"],
  },
  {
    id: 3,
    title: "ChatGPT, DeepSeek, Grok and 30+ More AI Marketing Assistants",
    instructors: "Anton Voroniuk, Anton Voroniuk Support",
    rating: 4.4,
    reviews: 526,
    price: 549,
    originalPrice: 799,
    image: "https://img-c.udemycdn.com/course/240x135/5672302_cfed.jpg",
    badges: ["Premium"],
    category: "Business Analytics & Intelligence",
    topics: ["ChatGPT", "Artificial Intelligence (AI)"],
  },
  {
    id: 4,
    title: "The Complete ChatGPT Guide From Zero to Hero - 2025",
    instructors: "A.M.A.M Mubeen (Expert In Tally &",
    rating: 4.2,
    reviews: 477,
    price: 499,
    originalPrice: 799,
    image: "https://img-c.udemycdn.com/course/240x135/5672302_cfed.jpg",
    badges: [],
    category: "IT Certifications",
    topics: ["ChatGPT"],
  },
  {
    id: 5,
    title: "Python for Data Science and Machine Learning Bootcamp",
    instructors: "Jose Portilla",
    rating: 4.6,
    reviews: 125789,
    price: 649,
    originalPrice: 3499,
    image: "https://img-c.udemycdn.com/course/240x135/5170404_d282_9.jpg",
    badges: ["Premium", "Bestseller"],
    category: "Data Science",
    topics: ["Python", "Data Science", "Machine Learning"],
  },
  {
    id: 6,
    title: "Machine Learning A-Z: Hands-On Python & R In Data Science",
    instructors: "Kirill Eremenko, Hadelin de Ponteves",
    rating: 4.5,
    reviews: 158964,
    price: 549,
    originalPrice: 3299,
    image: "https://img-c.udemycdn.com/course/240x135/3600048_b195_20.jpg",
    badges: ["Premium", "Bestseller"],
    category: "Data Science",
    topics: ["Machine Learning", "Python", "Data Science"],
  },
  {
    id: 7,
    title: "Deep Learning Specialization",
    instructors: "Andrew Ng",
    rating: 4.8,
    reviews: 45698,
    price: 749,
    originalPrice: 4999,
    image: "https://img-c.udemycdn.com/course/240x135/5170404_d282_9.jpg",
    badges: ["Premium", "Bestseller"],
    category: "Data Science",
    topics: ["Deep Learning", "Machine Learning", "Artificial Intelligence (AI)"],
  },
  {
    id: 8,
    title: "Statistics for Data Science and Business Analysis",
    instructors: "365 Careers",
    rating: 4.5,
    reviews: 28745,
    price: 449,
    originalPrice: 1999,
    image: "https://img-c.udemycdn.com/course/240x135/5170404_d282_9.jpg",
    badges: ["Premium"],
    category: "Data Science",
    topics: ["Statistics", "Data Science, Machine Learning"],
  },
  {
    id: 9,
    title: "Natural Language Processing with Python",
    instructors: "Lazy Programmer Inc.",
    rating: 4.6,
    reviews: 12458,
    price: 649,
    originalPrice: 2999,
    image: "https://img-c.udemycdn.com/course/240x135/5170404_d282_9.jpg",
    badges: ["Premium"],
    category: "Data Science",
    topics: ["Natural Language Processing", "Python", "Artificial Intelligence (AI)"],
  },
  {
    id: 10,
    title: "Web Development Bootcamp 2025",
    instructors: "Colt Steele",
    rating: 4.7,
    reviews: 215478,
    price: 549,
    originalPrice: 3499,
    image: "https://img-c.udemycdn.com/course/240x135/5170404_d282_9.jpg",
    badges: ["Premium", "Bestseller"],
    category: "Web Development",
    topics: ["Python", "JavaScript"],
  },
  {
    id: 11,
    title: "Leadership: Practical Leadership Skills",
    instructors: "Chris Croft",
    rating: 4.5,
    reviews: 32145,
    price: 449,
    originalPrice: 1999,
    image: "https://img-c.udemycdn.com/course/240x135/3600048_b195_20.jpg",
    badges: ["Premium", "Bestseller"],
    category: "Leadership",
    topics: [],
  },
  {
    id: 12,
    title: "Business Intelligence with Power BI",
    instructors: "Maven Analytics",
    rating: 4.6,
    reviews: 18745,
    price: 549,
    originalPrice: 2499,
    image: "https://img-c.udemycdn.com/course/240x135/3600048_b195_20.jpg",
    badges: ["Premium"],
    category: "Business Analytics & Intelligence",
    topics: ["Data Science"],
  },
]

export const realEstateListings: Course[] = [
  {
    id: 1,
    title: "Luxury 3BHK Apartment in Downtown LA",
    instructors: "Elite Realty Group",
    rating: 4.7,
    reviews: 125,
    price: 1200000,
    originalPrice: 1300000,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&h=250&fit=crop",
    badges: ["Luxury", "Hot Deal"],
    category: "Residential Properties",
    topics: ["Residential Properties", "Real Estate Investing"],
  },
  {
    id: 2,
    title: "Spacious 4BHK Villa with Garden",
    instructors: "Prime Estates",
    rating: 4.8,
    reviews: 98,
    price: 1850000,
    originalPrice: 1950000,
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=400&h=250&fit=crop",
    badges: ["Premium", "New Listing"],
    category: "Residential Properties",
    topics: ["Commercial Real Estate", "Residential Properties, Luxury Real Estate"],
  },
  {
    id: 3,
    title: "Modern Studio Apartment near Central Park",
    instructors: "Urban Realty Co.",
    rating: 4.6,
    reviews: 210,
    price: 650000,
    originalPrice: 700000,
    image: "https://images.unsplash.com/photo-1592595896551-a7b31c1776d7?w=400&h=250&fit=crop",
    badges: ["Best Seller"],
    category: "Real Estate Investing",
    topics: ["Mortgage & Financing", "Commercial Real Estate"],
  },
  {
    id: 4,
    title: "Cozy 2BHK House for Rent",
    instructors: "Home Sweet Homes",
    rating: 4.5,
    reviews: 87,
    price: 2500,
    originalPrice: 2800,
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&h=250&fit=crop",
    badges: ["Pet Friendly"],
    category: "Residential Properties",
    topics: ["Commercial Real Estate", "Mortgage & Financing", "Luxury Real Estate"],
  },
  {
    id: 5,
    title: "Commercial Office Space in Silicon Valley",
    instructors: "Silicon Valley Properties",
    rating: 4.9,
    reviews: 143,
    price: 5000000,
    originalPrice: 5500000,
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&h=250&fit=crop",
    badges: ["High Demand"],
    category: "Residential Properties",
    topics: ["Mortgage & Financing", "Commercial Real Estate"],
  }
];

export const popularCourses = [
  {
    id: 1,
    title: "100 Days of Code: The Complete Python Pro Bootcamp for 2025",
    instructors: ["Dr. Angela Yu", "Developer and Lead Instructor"],
    rating: 4.7,
    reviewCount: 241640,
    students: 1452344,
    price: 549,
    originalPrice: 1699,
    image: "https://img-c.udemycdn.com/course/240x135/2776760_f176_10.jpg",
  },
  {
    id: 2,
    title: "The Complete Full-Stack Web Development Bootcamp",
    instructors: ["Dr. Angela Yu", "Developer and Lead Instructor"],
    rating: 4.7,
    reviewCount: 122055,
    students: 654321,
    price: 499,
    originalPrice: 1699,
    image: "https://img-c.udemycdn.com/course/240x135/2776760_f176_10.jpg",
  },
  {
    id: 3,
    title: "[NEW] Ultimate AWS Certified Cloud Practitioner - CLF-C02 2025",
    instructors: ["Stephane Maarek", "AWS Certified Cloud Practitioner"],
    rating: 4.7,
    reviewCount: 153075,
    students: 876543,
    price: 549,
    originalPrice: 1699,
    image: "https://img-c.udemycdn.com/course/240x135/3142166_a637_3.jpg",
  },
  {
    id: 4,
    title: "Ultimate AWS Certified Solutions Architect Associate SAA-C03 2025",
    instructors: ["Stephane Maarek", "AWS Certified Cloud Practitioner"],
    rating: 4.7,
    reviewCount: 187654,
    students: 932456,
    price: 549,
    originalPrice: 1699,
    image: "https://img-c.udemycdn.com/course/240x135/3142166_a637_3.jpg",
  },
  {
    id: 5,
    title: "Ultimate AWS Certified Solutions Architect Associate SAA-C03 2025",
    instructors: ["Stephane Maarek", "AWS Certified Cloud Practitioner"],
    rating: 4.7,
    reviewCount: 187654,
    students: 932456,
    price: 549,
    originalPrice: 1699,
    image: "https://img-c.udemycdn.com/course/240x135/6100015_1979_4.jpg",
  },
  {
    id: 6,
    title: "Ultimate AWS Certified Solutions Architect Associate SAA-C03 2025",
    instructors: ["Stephane Maarek", "AWS Certified Cloud Practitioner"],
    rating: 4.7,
    reviewCount: 187654,
    students: 932456,
    price: 549,
    originalPrice: 1699,
    image: "https://img-c.udemycdn.com/course/240x135/1570206_26c6_6.jpg",
  },
  {
    id: 7,
    title: "Ultimate AWS Certified Solutions Architect Associate SAA-C03 2025",
    instructors: ["Stephane Maarek", "AWS Certified Cloud Practitioner"],
    rating: 4.7,
    reviewCount: 187654,
    students: 932456,
    price: 549,
    originalPrice: 1699,
    image: "https://img-c.udemycdn.com/course/240x135/5993822_2c2a_7.jpg",
  }
]

export const popularProperties = [
  {
    id: 1,
    title: "Luxury 3BHK Apartment in Downtown LA",
    instructors: ["John Doe", "Real Estate Agent"],
    rating: 4.8,
    reviewCount: 154,
    students: 120, // Representing inquiries or interested buyers
    price: 3500,
    originalPrice: 4000,
    image: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
  },
  {
    id: 2,
    title: "Modern 2BHK Condo with Ocean View",
    instructors: ["Jane Smith", "Luxury Properties"],
    rating: 4.7,
    reviewCount: 98,
    students: 85,
    price: 2800,
    originalPrice: 3200,
    image: "https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg",
  },
  {
    id: 3,
    title: "Spacious 4BHK Villa with Private Pool",
    instructors: ["Robert Johnson", "Villa Specialist"],
    rating: 4.9,
    reviewCount: 76,
    students: 65,
    price: 5000,
    originalPrice: 5500,
    image: "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
  },
  {
    id: 4,
    title: "Cozy Studio Apartment in New York",
    instructors: ["Emily Davis", "Rental Expert"],
    rating: 4.5,
    reviewCount: 230,
    students: 190,
    price: 2200,
    originalPrice: 2500,
    image: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg",
  },
  {
    id: 5,
    title: "Modern 3BHK Townhouse with Garage",
    instructors: ["Michael Brown", "Townhouse"],
    rating: 4.8,
    reviewCount: 110,
    students: 95,
    price: 4500,
    originalPrice: 4800,
    image: "https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg",
  },
  {
    id: 6,
    title: "Penthouse Suite with Skyline View",
    instructors: ["Sophia Wilson", "High-Rise"],
    rating: 4.9,
    reviewCount: 89,
    students: 72,
    price: 7000,
    originalPrice: 7500,
    image: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg",
  },
  {
    id: 7,
    title: "Elegant 2BHK Apartment in Seattle",
    instructors: ["Daniel Lee", "Seattle Real Estate"],
    rating: 4.6,
    reviewCount: 125,
    students: 110,
    price: 3100,
    originalPrice: 3400,
    image: "https://images.pexels.com/photos/8136925/pexels-photo-8136925.jpeg",
  }
];

export const luxuryHomes = [
  {
    id: 1,
    price: 2050000,
    beds: 5,
    baths: 3,
    sqft: 3200,
    address: "1729 42nd Avenue SE",
    city: "Spokane",
    state: "WA",
    zip: "99208",
    type: "Multi-Family Home",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=600&h=400&auto=format&fit=crop",
    new: true,
  },
  {
    id: 2,
    price: 1350000,
    beds: 4,
    baths: 3,
    sqft: 2400,
    address: "1508 E Creekview Dr",
    city: "Spokane",
    state: "WA",
    zip: "99207",
    type: "Single-Family Home",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=600&h=400&auto=format&fit=crop",
    new: true,
  },
  {
    id: 3,
    price: 1200000,
    beds: 4,
    baths: 3,
    sqft: 2100,
    address: "1426 N Lincoln St",
    city: "Spokane",
    state: "WA",
    zip: "99207",
    type: "Multi-Family Home",
    image: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?q=80&w=600&h=400&auto=format&fit=crop",
    new: true,
    lot: 0.25,
  },
  {
    id: 4,
    price: 4300000,
    beds: 6,
    baths: 7,
    sqft: 5267,
    address: "4507 N Boulder Park Ln",
    city: "Spokane",
    state: "WA",
    zip: "99207",
    type: "Single-Family Home",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=600&h=400&auto=format&fit=crop",
    new: true,
  },
  {
    id: 5,
    price: 4300000,
    beds: 6,
    baths: 7,
    sqft: 5267,
    address: "4507 N Boulder Park Ln",
    city: "Spokane",
    state: "WA",
    zip: "99207",
    type: "Single-Family Home",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=600&h=400&auto=format&fit=crop",
    new: true,
  },
  {
    id: 6,
    price: 4300000,
    beds: 6,
    baths: 7,
    sqft: 5267,
    address: "4507 N Boulder Park Ln",
    city: "Spokane",
    state: "WA",
    zip: "99207",
    type: "Single-Family Home",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=600&h=400&auto=format&fit=crop",
    new: true,
  },
  {
    id: 7,
    price: 4300000,
    beds: 6,
    baths: 7,
    sqft: 5267,
    address: "4507 N Boulder Park Ln",
    city: "Spokane",
    state: "WA",
    zip: "99207",
    type: "Single-Family Home",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=600&h=400&auto=format&fit=crop",
    new: true,
  },
]

export const testimonials = [
  {
    id: 1,
    text: "Because of this course I was able to clear multiple interviews. Thanks for making such wonderful content.",
    author: "Richard S.",
    course: "Business Intelligence (BI)",
  },
  {
    id: 2,
    text: "This has helped me so much in my career. I started as a frontend engineer and eventually transitioned to full stack engineer with the help of this course.",
    author: "Charlotte W.",
    course: "Go-getting course",
  },
  {
    id: 3,
    text: "Today I am a software developer, and I consider a significant part of my success to the solid foundation laid by this course.",
    author: "Martha A.",
    course: "Java course",
  },
  {
    id: 4,
    text: "I would highly recommend this Web Development Bootcamp to anyone interested in pursuing a career in web development. It provides the foundation to enhance their skills in the field.",
    author: "Anna P.",
    course: "Web Development course",
  },
]

export const footerLinks = [
  { name: "About us", href: "#" },
  { name: "Careers", href: "#" },
  { name: "Accessibility", href: "#" },
  { name: "Feedback", href: "#" },
  { name: "Media room", href: "#" },
  { name: "Ad Choices", href: "#" },
  { name: "Advertise with us", href: "#" },
  { name: "Agent support", href: "#" },
  { name: "Privacy", href: "#" },
  { name: "Terms", href: "#" },
  { name: "Home Made", href: "#" },
  { name: "Tech Blog", href: "#" },
  { name: "Agent Blog", href: "#" },
  { name: "Sitemap", href: "#" },
  { name: "Do Not Sell or Share My Personal Information", href: "#" },
]

export const socialLinks = [
  { name: "Facebook", href: "#", icon: "facebook" },
  { name: "Twitter", href: "#", icon: "twitter" },
  { name: "LinkedIn", href: "#", icon: "linkedin" },
  { name: "Instagram", href: "#", icon: "instagram" },
  { name: "YouTube", href: "#", icon: "youtube" },
]

export const trustedCompanies = [
  { id: 1, name: "Volkswagen", logo: "https://cms-images.udemycdn.com/content/mueb2ve09x/svg/volkswagen_logo.svg?position=c&quality=80&x.app=portals" },
  { id: 2, name: "Samsung", logo: "https://cms-images.udemycdn.com/content/2gevcc0kxt/svg/samsung_logo.svg?position=c&quality=80&x.app=portals" },
  { id: 3, name: "Cisco", logo: "https://cms-images.udemycdn.com/content/mueb2ve09x/svg/cisco_logo.svg?position=c&quality=80&x.app=portals" },
  { id: 4, name: "Vimeo", logo: "https://cms-images.udemycdn.com/content/ryaowrcjb2/svg/vimeo_logo_resized-2.svg?position=c&quality=80&x.app=portals" },
  { id: 5, name: "P&G", logo: "https://cms-images.udemycdn.com/content/bthyo156te/svg/procter_gamble_logo.svg?position=c&quality=80&x.app=portals" },
  { id: 6, name: "Hewlett Packard Enterprise", logo: "https://cms-images.udemycdn.com/content/luqe0d6mx2/svg/hewlett_packard_enterprise_logo.svg?position=c&quality=80&x.app=portals" },
  { id: 7, name: "Citi", logo: "https://cms-images.udemycdn.com/content/siaewwmkch/svg/citi_logo.svg?position=c&quality=80&x.app=portals" },
  { id: 8, name: "Ericsson", logo: "https://cms-images.udemycdn.com/content/swmv0okrlh/svg/ericsson_logo.svg?position=c&quality=80&x.app=portals" },
];

export const ELearningButtons = [
  { label: "My Learnings", index: 0 },
  { label: "Live Classes", index: 1 },
  { label: "Teach on CU", index: 2 },
  { label: "Pricing & Subscriptions", index: 3 },
  { label: "Trainings & Certificates", index: 4 },
  { label: "Contact Us", index: 5 },
];

export const ElearningHeroSection = {
  title: "The #1 site for lifelong learners & experienced trainers.",
  buttons: ELearningButtons.map(button => button.label),
  imageSrc: "https://s.udemycdn.com/browse_components/billboard/fallback_banner_image_udlite.jpg",
};

export const RealEstateButtons = [
  { label: "Home", index: 0 },
  { label: "Buy", index: 1 },
  { label: "Rent", index: 2 },
  { label: "Sell", index: 3 },
  { label: "Commercial", index: 4 },
  { label: "Mortgage", index: 5 },
  { label: "Agents", index: 6 },
  { label: "Market Trends", index: 7 },
  { label: "Contact Us", index: 8 },
];

export const RealEstateHeroSection = {
  title: "Your #1 Destination for Buying, Selling & Renting Homes.",
  buttons: RealEstateButtons.map(button => button.label),
  imageSrc: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1600&h=600&auto=format&fit=crop",
};

export const searchOptionsElearning = ["Courses", "Trainers", "Certificates"];
export const searchOptionsRealEstate = ["Buy", "Rent", "Sell", "Commercial", "Mortgage", "Agents", "Market Trends"];

export const userRoles = ["Student", "Trainer"];

export const ctaContent = {
  heading: "Come Teach with us?",
  backgroundImage: "/ebook.png"
};
export const realEstatectaContent = {
  heading: "Find Your Dream Home Today?",
  backgroundImage: "/realEstate.png"
};

export const courses = [
  {
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=600&h=400&crop=faces&fit=crop",
    title: "Data Science & Machine Learning",
    description: "Expert in AI, Data Science, and Deep Learning with 10+ years of experience",
    instructors: "Krish Naik",
    rating: 4.8,
    ratingsCount: 9800,
    totalHours: 1500,
    lectures: 120,
    level: "Expert",
    price: 499,
    originalPrice: 2999,
    new: true,
  },
  {
    image: "https://images.unsplash.com/photo-1521119989659-a83eee488004?q=80&w=600&h=400&crop=faces&fit=crop",
    title: "JavaScript & Web Development",
    description: "Full-Stack JavaScript Developer with expertise in React, Node.js, and TypeScript",
    instructors: "John Doe",
    rating: 4.7,
    ratingsCount: 8700,
    totalHours: 1200,
    lectures: 200,
    level: "Intermediate",
    price: 699,
    originalPrice: 3499,
    new: false,
  },
  {
    image: "https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=600&h=400&crop=faces&fit=crop",
    title: "React & Next.js Development",
    description: "Passionate Frontend Engineer teaching modern web development best practices",
    instructors: "Emily White",
    rating: 4.9,
    ratingsCount: 1020,
    totalHours: 1000,
    lectures: 180,
    level: "Advanced",
    price: 899,
    originalPrice: 3999,
    new: true,
  },
  {
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=600&h=400&crop=faces&fit=crop",
    title: "Full-Stack Web Development",
    description: "Full-stack engineer covering everything from backend APIs to frontend UI",
    instructors: "David Green",
    rating: 4.8,
    ratingsCount: 1130,
    totalHours: 1400,
    lectures: 250,
    level: "Expert",
    price: 899,
    originalPrice: 3999,
    new: true,
  },
  {
    image: "https://images.unsplash.com/photo-1554151228-14d9def656e4?q=80&w=600&h=400&crop=faces&fit=crop",
    title: "Machine Learning & Web Development",
    description: "Helping designers master UX, UI, and product design fundamentals",
    instructors: "Sophia Brown",
    rating: 4.6,
    ratingsCount: 7200,
    totalHours: 800,
    lectures: 150,
    level: "Beginner to Advanced",
    price: 799,
    originalPrice: 3499,
    new: false,
  },
  {
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=600&h=400&crop=faces&fit=crop",
    title: "Cybersecurity & Ethical Hacking",
    description: "Cybersecurity professional specializing in penetration testing and ethical hacking",
    instructors: "James Wilson",
    rating: 4.7,
    ratingsCount: 8600,
    totalHours: 1100,
    lectures: 220,
    level: "Intermediate",
    price: 899,
    originalPrice: 3999,
    new: true,
  },
];


export const propertyDetails = {
  name: "Top Trainers",
  location: "All Locations",
  properties: luxuryHomes,
};

export const trustedMessage = "Trusted by over 16,000 companies and millions of learners around the world";
export const testimonial = "See what others are achieving through learning";

export const initialModules = [
  { name: "COURSE_MANAGEMENT", read: true, create: true, update: true, delete: false },
  { name: "USER_MANAGEMENT", read: true, create: true, update: true, delete: true },
  { name: "QUIZ_MANAGEMENT", read: true, create: true, update: true, delete: false },
  { name: "CONTENT_MANAGEMENT", read: true, create: true, update: true, delete: false },
  { name: "REPORTS", read: true, create: false, update: false, delete: false },
  { name: "NOTIFICATIONS", read: true, create: false, update: false, delete: false },
  { name: "SETTINGS", read: true, create: false, update: true, delete: false },
  { name: "FEEDBACK", read: true, create: true, update: false, delete: false },
]


// Restaurants

export const RestaurantButtons = [
  { label: "Home", index: 0 },
  { label: "Menu", index: 1 },
  { label: "Order Online", index: 2 },
  { label: "Reservations", index: 3 },
  { label: "Specials", index: 4 },
  { label: "Catering", index: 5 },
  { label: "Events", index: 6 },
  { label: "Reviews", index: 7 },
  { label: "Contact Us", index: 8 },
];

export const RestaurantHeroSection = {
  title: "Delicious Meals, Anytime, Anywhere!",
  buttons: RestaurantButtons.map(button => button.label),
  imageSrc: "https://assets.architecturaldigest.in/photos/65e9631d9719efc62841b9d5/16:9/w_2560%2Cc_limit/DSC07703_11zon.jpg",
};

export const restaurantCategories: string[] = [
  "Local Restaurants",
  "Japanese",
  "Street Food Adventures",
  "American",
];

export const restaurantPopularTopics = [
  { name: "Local Restaurants", count: "10M+ viewers" },
  { name: "Trending Dishes", count: "7M+ viewers" },
  { name: "Healthy Eating", count: "5M+ viewers" },
  { name: "Street Food Adventures", count: "6.5M+ viewers" },
  { name: "Fine Dining Experiences", count: "4M+ viewers" },
];

export const restaurantListings: Course[] = [
  {
    id: 1,
    title: "Authentic Italian Pasta & Pizza",
    instructors: "La Bella Italia",
    rating: 4.8,
    reviews: 320,
    price: 20,
    originalPrice: 25,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=250&fit=crop",
    badges: ["Best Seller", "Customer Favorite"],
    category: "Local Restaurants",
    topics: ["Trending Dishes", "Fine Dining Experiences", "Local Restaurants"],
  },
  {
    id: 2,
    title: "Sushi & Sashimi Special Platter",
    instructors: "Tokyo Bites",
    rating: 4.9,
    reviews: 275,
    price: 35,
    originalPrice: 40,
    image: "https://images.unsplash.com/photo-1562158074-1602c2db2c76?w=400&h=250&fit=crop",
    badges: ["Premium", "Fresh Ingredients"],
    category: "Japanese Cuisine",
    topics: ["Street Food Adventures", "Sashimi", "Healthy Eating"],
  },
  {
    id: 3,
    title: "BBQ Ribs & Smoked Brisket",
    instructors: "Texas Smokehouse",
    rating: 4.7,
    reviews: 198,
    price: 28,
    originalPrice: 32,
    image: "https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=400&h=250&fit=crop",
    badges: ["Grill Master", "Crowd Favorite"],
    category: "Local Restaurants",
    topics: ["Street Food Adventures", "Slow Cooked", "Meat Lovers"],
  },
  {
    id: 4,
    title: "Vegan Buddha Bowl & Smoothies",
    instructors: "Green Earth Cafe",
    rating: 4.6,
    reviews: 250,
    price: 18,
    originalPrice: 22,
    image: "https://images.unsplash.com/photo-1523181300153-daa1de7bb0a4?w=400&h=250&fit=crop",
    badges: ["Vegan", "Gluten-Free"],
    category: "Local Restaurants",
    topics: ["Plant-Based", "Organic", "Local Restaurants"],
  },
  {
    id: 5,
    title: "Classic French Pastries & Desserts",
    instructors: "Parisian Delights",
    rating: 4.9,
    reviews: 312,
    price: 15,
    originalPrice: 18,
    image: "https://images.unsplash.com/photo-1541592106381-e175b94c74b5?w=400&h=250&fit=crop",
    badges: ["Sweet Tooth", "Authentic"],
    category: "Desserts & Pastries",
    topics: ["French Bakery", "Street Food Adventures", "Cakes"],
  }
];

